[Rainmeter]


[Metadata]
Name=Hex H Suite
Author=Zerogate309
Information=Styles for the Suite
FileVersion=2022-12
License=Creative Commons Attribution-Non-Commercial-Share Alike 4.0

; ############ Index Styles ############
; ========== Font_Styles ==========
; ========== Base Styles Standard ==========
; ========== Base Styles L ==========
; ========== Base Styles XL ==========
; ========== Other Styles ==========
; ========== Bar-Styles ==========
; ========== Styles for Graph ==========
; ========== Styles for Histogram ==========
; ========== Band-Styles ==========
; ========== Styles for Color Palette ==========
; ========== WebRadio Styles ==========


; ######## Font_Styles ########
; Notation: Style_Font/FontFace/Fontsize/Color/alignment
; Example: Style_Font_1_18_3_C = Style_Font... / FontFace=1 / FontSize=18 / Color= 3 / Alignment=Center

;--- Skin Color Match ---
;Color 1 = Back
;Color 2 = Frame
;Color 3 = Text 1
;Color 4 = Text 2
;Color 5 = BarBack
;Color 6 = Bar
;Color 7 = Band
;Color 8 = Graph
;Color 9 = Icons
;Color B = Border

; ---- Fonts ----

;FontFace_1=Elemental End
;FontFace_2=Tahoma

; ---- Font Sizes ----
;FontSize_20 = 20
;FontSize_18 = 18
;FontSize_16 = 16
;FontSize_14 = 15
;FontSize_14 = 14
;FontSize_13 = 13
;FontSize_12 = 12
;FontSize_11 = 11
;FontSize_10 = 10
;FontSize_09 = 09
;FontSize_08 = 08
;FontSize_07 = 07
;FontSize_06 = 06

; ======== FontFace 1 ========

[Style_Font_1_08_3_C]
FontFace=#FontFace_1#
FontSize=#FontSize_08#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_1_09_3_C]
FontFace=#FontFace_1#
FontSize=#FontSize_09#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_1_10_3_L]
FontFace=#FontFace_1#
FontSize=#FontSize_10#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Left
AntiAlias=1

[Style_Font_1_10_3_C]
FontFace=#FontFace_1#
FontSize=#FontSize_10#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_1_10_3_R]
FontFace=#FontFace_1#
FontSize=#FontSize_10#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Right
AntiAlias=1

[Style_Font_1_11_3_C]
FontFace=#FontFace_1#
FontSize=#FontSize_11#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_1_13_3_C]
FontFace=#FontFace_1#
FontSize=#FontSize_13#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_1_13_3_R]
FontFace=#FontFace_1#
FontSize=#FontSize_13#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Right
AntiAlias=1

[Style_Font_1_13_4_C]
FontFace=#FontFace_1#
FontSize=#FontSize_13#
FontColor=#Color4#,#Color4Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_1_14_3_C]
FontFace=#FontFace_1#
FontSize=#FontSize_14#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_1_16_3_L]
FontFace=#FontFace_1#
FontSize=#FontSize_16#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Left
AntiAlias=1

[Style_Font_1_16_3_C]
FontFace=#FontFace_1#
FontSize=#FontSize_16#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_1_16_3_R]
FontFace=#FontFace_1#
FontSize=#FontSize_16#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Right
AntiAlias=1

[Style_Font_1_18_3_C]
FontFace=#FontFace_1#
FontSize=#FontSize_18#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1


; ======== FontFace 2 ========

[Style_Font_2_07_4_C]
FontFace=#FontFace_2#
FontSize=#FontSize_07#
FontColor=#Color4#,#Color4Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_2_08_1_C]
FontFace=#FontFace_2#
FontSize=#FontSize_08#
FontColor=#Color1#,#Color1Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_2_08_1_R]
FontFace=#FontFace_2#
FontSize=#FontSize_08#
FontColor=#Color1#,#Color1Alpha#
StringAlign=Right
AntiAlias=1

[Style_Font_2_08_3_L]
FontFace=#FontFace_2#
FontSize=#FontSize_08#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Left
AntiAlias=1

[Style_Font_2_08_3_C]
FontFace=#FontFace_2#
FontSize=#FontSize_08#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_2_08_3_R]
FontFace=#FontFace_2#
FontSize=#FontSize_08#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Right
AntiAlias=1

[Style_Font_2_08_3_R_S]
FontFace=#FontFace_2#
FontSize=#FontSize_08#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Right
StringEffect=SHADOW
FontEffectColor=0,0,0,150
AntiAlias=1

[Style_Font_2_08_4_L]
FontFace=#FontFace_2#
FontSize=#FontSize_08#
FontColor=#Color4#,#Color4Alpha#
StringAlign=Left
AntiAlias=1

[Style_Font_2_08_4_C]
FontFace=#FontFace_2#
FontSize=#FontSize_08#
FontColor=#Color4#,#Color4Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_2_08_4_R]
FontFace=#FontFace_2#
FontSize=#FontSize_08#
FontColor=#Color4#,#Color4Alpha#
StringAlign=Right
AntiAlias=1

[Style_Font_2_08_4_R_S]
FontFace=#FontFace_2#
FontSize=#FontSize_08#
FontColor=#Color4#,#Color4Alpha#
StringAlign=Right
StringEffect=SHADOW
FontEffectColor=0,0,0,150
AntiAlias=1

[Style_Font_2_09_4_C]
FontFace=#FontFace_2#
FontSize=#FontSize_09#
FontColor=#Color4#,#Color4Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_2_10_3_L]
FontFace=#FontFace_2#
FontSize=#FontSize_10#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Left
AntiAlias=1

[Style_Font_2_10_3_C]
FontFace=#FontFace_2#
FontSize=#FontSize_10#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_2_10_4_L]
FontFace=#FontFace_2#
FontSize=#FontSize_10#
FontColor=#Color4#,#Color4Alpha#
StringAlign=Left
AntiAlias=1

[Style_Font_2_10_4_C]
FontFace=#FontFace_2#
FontSize=#FontSize_10#
FontColor=#Color4#,#Color4Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_2_11_3_L]
FontFace=#FontFace_2#
FontSize=#FontSize_11#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Left
AntiAlias=1

[Style_Font_2_11_3_C]
FontFace=#FontFace_2#
FontSize=#FontSize_11#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_2_11_4_C]
FontFace=#FontFace_2#
FontSize=#FontSize_11#
FontColor=#Color4#,#Color4Alpha#
StringAlign=Center
AntiAlias=1

[Style_Font_2_12_3_L]
FontFace=#FontFace_2#
FontSize=#FontSize_12#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Left
AntiAlias=1

[Style_Font_2_12_3_C]
FontFace=#FontFace_2#
FontSize=#FontSize_12#
FontColor=#Color3#,#Color3Alpha#
StringAlign=Center
AntiAlias=1

; ---- Base Styles Standard ----
; -- Background_0 --
[Style_Background_0]
ImageName=#@#\Frames\Hex H - S_Back.png
ImageTint=#Color1#,#Color1Alpha#
X=10
; -- Frame_0 -----
[Style_Frame_0]
ImageName=#@#\Frames\Hex H - S_Frame.png
ImageTint=#Color2#,#Color2Alpha#
X=10

; ---- Base Styles M ----
; -- Background_0M --
[Style_Background_0M]
ImageName=#@#\Frames\Hex H - M_Back.png
ImageTint=#Color1#,#Color1Alpha#
X=10
Y=30
; -- Frame_0M --
[Style_Frame_0M]
ImageName=#@#\Frames\Hex H - M_Frame.png
ImageTint=#Color2#,#Color2Alpha#
X=10
Y=30

; ---- Base Styles L ----
; -- Background_0L --
[Style_Background_0L]
ImageName=#@#\Frames\Hex H - L_Back.png
ImageTint=#Color1#,#Color1Alpha#
X=10
Y=30
; -- Frame_0L --
[Style_Frame_0L]
ImageName=#@#\Frames\Hex H - L_Frame.png
ImageTint=#Color2#,#Color2Alpha#
X=10
Y=30

; ---- Base Styles XL ----
; -- Background_0XL --
[Style_Background_0XL]
ImageName=#@#\Frames\Hex H - XL_Back.png
ImageTint=#Color1#,#Color1Alpha#
X=10
Y=40
; -- Frame_0XL --
[Style_Frame_0XL]
ImageName=#@#\Frames\Hex H - XL_Frame.png
ImageTint=#Color2#,#Color2Alpha#
X=10
Y=40
; -- Icon_0XL --
[Style_Icon_0XL]
ImageTint=#Color9#,#Color9Alpha#
W=35
H=35

; -- Close Button L --
[Style_Close_Back_0L]
X=280
Shape=Rectangle 0,0,24,24,5 | Fill Color #Color3# | StrokeWidth 0 | Stroke Color #Color2#

[Style_Close_0L]
ImageName=#@#\Icons\Icon-Square Close.png
ImageTint=#Color2#,#Color2Alpha#
X=r
Y=r
W=24
H=24
ToolTipText=Close

; -- Close Button XL --
[Style_Close_Back_0XL]
X=425
Shape=Rectangle 0,0,30,30,5 | Fill Color #Color3# | StrokeWidth 0 | Stroke Color #Color2#

[Style_Close_0XL]
ImageName=#@#\Icons\Icon-Square Close.png
ImageTint=#Color2#,#Color2Alpha#
X=r
Y=r
W=30
H=30
ToolTipText=Close

; -------- Other Styles --------

; -- Border --
[Style_Border_0]
ImageTint=#ColorB#,#ColorBAlpha#
AntiAlias=1

[Style_Border_Top]
ImageTint=#ColorB#,#ColorBAlpha#
X=(110+#Padding#)r
Y=r
AntiAlias=1

[Style_Border_Side]
ImageTint=#ColorB#,#ColorBAlpha#
X=r
Y=(187+#Padding#)r
AntiAlias=1

[Style_Border_Right_1]
ImageTint=#ColorB#,#ColorBAlpha#
X=([Border_Right_Main_00:X])
AntiAlias=1

[Style_Border_Right_2]
ImageTint=#ColorB#,#ColorBAlpha#
X=([Border_Top_Right_Edge:X])
AntiAlias=1

[Style_Border_Bottom]
ImageTint=#ColorB#,#ColorBAlpha#
X=(110+#Padding#)r
Y=r
AntiAlias=1

; -- Icon_0 --
[Style_Icon_0]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1

; -- Icon_1 --
[Style_Icon_1]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1

; -- Icon W=12; H=12 Color 1 --
[Style_Icon_12_1]
ImageTint=#Color1#,#Color1Alpha#
AntiAlias=1
W=12
H=12

; -- Icon W=12; H=12 Color 2 --
[Style_Icon_12_2]
ImageTint=#Color2#,#Color2Alpha#
AntiAlias=1
W=12
H=12

; -- Icon W=12; H=12 Color 3 --
[Style_Icon_12_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=12
H=12

; -- Icon W=12; H=12 Color 4 --
[Style_Icon_12_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=12
H=12

; -- Icon W=14; H=14 Color 1  --
[Style_Icon_14_1]
ImageTint=#Color1#,#Color1Alpha#
AntiAlias=1
W=14
H=14

; -- Icon W=14; H=14 Color 3 --
[Style_Icon_14_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=14
H=14

; -- Icon W=14; H=14 Color 4 --
[Style_Icon_14_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=14
H=14

; -- Icon W=14; H=14 Color 9 --
[Style_Icon_14_9]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=14
H=14

; -- Icon W=16; H=16 Color 3 --
[Style_Icon_16_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=16
H=16

; -- Icon W=16; H=16 Color 4 --
[Style_Icon_16_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=16
H=16

; -- Icon W=16; H=16 Color 9 --
[Style_Icon_16_9]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=16
H=16

; -- Icon W=18; H=18 Color 2 --
[Style_Icon_18_2]
ImageTint=#Color2#,#Color2Alpha#
AntiAlias=1
W=18
H=18

; -- Icon W=18; H=18 Color 3 --
[Style_Icon_18_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=18
H=18

; -- Icon W=18; H=18 Color 4 --
[Style_Icon_18_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=18
H=18

; -- Icon W=18; H=18 Color 9 --
[Style_Icon_18_9]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=18
H=18

; -- Icon W=20; H=20 Color 2 --
[Style_Icon_20_2]
ImageTint=#Color2#,#Color2Alpha#
AntiAlias=1
W=20
H=20

; -- Icon W=20; H=20 Color 3 --
[Style_Icon_20_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=20
H=20

; -- Icon W=20; H=20 Color 4 --
[Style_Icon_20_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=20
H=20

; -- Icon W=20; H=20 Color 9 --
[Style_Icon_20_9]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=20
H=20

; -- Icon W=22; H=22 Color 2 --
[Style_Icon_22_2]
ImageTint=#Color2#,#Color2Alpha#
AntiAlias=1
W=22
H=22

; -- Icon W=22; H=22 Color 3 --
[Style_Icon_22_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=22
H=22

; -- Icon W=22; H=22 Color 4 --
[Style_Icon_22_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=22
H=22

; -- Icon W=22; H=22 Color 9 --
[Style_Icon_22_9]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=22
H=22

; -- Icon W=24; H=24 Color 2 --
[Style_Icon_24_2]
ImageTint=#Color2#,#Color2Alpha#
AntiAlias=1
W=24
H=24

; -- Icon W=24; H=24 Color 3 --
[Style_Icon_24_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=24
H=24

; -- Icon W=24; H=24 Color 4 --
[Style_Icon_24_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=24
H=24

; -- Icon W=24; H=24 Color 9 --
[Style_Icon_24_9]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=24
H=24

; -- Icon W=26; H=26 Color 9 --
[Style_Icon_26_9]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=26
H=26

; -- Icon W=28; H=28 Color 3 --
[Style_Icon_28_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=28
H=28

; -- Icon W=28; H=28 Color 4 --
[Style_Icon_28_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=28
H=28

; -- Icon W=28; H=28 Color 9 --
[Style_Icon_28_9]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=28
H=28

; -- Icon W=34; H=34 Color 3 --
[Style_Icon_34_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=34
H=34

; -- Icon W=34; H=34 Color 4 --
[Style_Icon_34_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=34
H=34

; -- Icon W=34; H=34 Color 9 --
[Style_Icon_34_9]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=34
H=34

; -- Icon W=38; H=38 Color 2 --
[Style_Icon_38_2]
ImageTint=#Color2#,#Color2Alpha#
AntiAlias=1
W=38
H=38

; -- Icon W=38; H=38 Color 9 --
[Style_Icon_38_9]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=38
H=38

; -- Icon W=48; H=48 Color 4 --
[Style_Icon_48_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=48
H=48

; -- Icon W=55; H=55 Color 3 --
[Style_Icon_55_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=55
H=55

; -- Icon W=55; H=55 Color 4 --
[Style_Icon_55_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=55
H=55

; -- Icon W=65; H=65 Color 3 --
[Style_Icon_65_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=65
H=65

; -- Icon W=65; H=65 Color 4 --
[Style_Icon_65_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=65
H=65

; -- Icon W=70; H=70 Color 3 --
[Style_Icon_70_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=70
H=70

; -- Icon W=70; H=70 Color 4 --
[Style_Icon_70_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=70
H=70

; -- Icon W=80; H=80 Color 3 --
[Style_Icon_80_3]
ImageTint=#Color3#,#Color3Alpha#
AntiAlias=1
W=80
H=80

; -- Icon W=80; H=80 Color 4 --
[Style_Icon_80_4]
ImageTint=#Color4#,#Color4Alpha#
AntiAlias=1
W=80
H=80

; -- Icon W=80; H=80 Color 9 --
[Style_Icon_80_9]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=80
H=80

; --- Style for Icon Drive 40x40px ---
[Style_IconDrv_40]
ImageTint=#Color9#,#Color9Alpha#
AntiAlias=1
W=40
H=40
ToolTipText=Click to Change Icon

; --- Style for Drive Text ---
[Style_Drive_Txt]
X=20r
Y=6R
W=28
H=22
SolidColor=#Color4#,#Color4Alpha#
ToolTipText=Click to Change Driveletter

; --- Style for Drive Number ---
[Style_Drive_No]
X=r
Y=-60r
ToolTipText=Drive Number (Skin)

; --- Image Tint ---
[Style_ImageTint]
ImageTint=200,200,200,200
AntiAlias=1
[Style_ImageTint_200]
ImageTint=200,200,200,200
AntiAlias=1

; --- Style for Separator ---
[Style_Separator]
SolidColor=#Color4#,#Color4Alpha#
W=80
H=1

; --- Style for ToolTipIcon Info ---
[Style_ToolTip_Info]
ToolTipTitle=Info
ToolTipIcon=#@#\Icons\Icon-ToolTip_Info.ico

; --- Style for ToolTipIcon Question ---
[Style_ToolTip_Question]
ToolTipTitle=Question
ToolTipIcon=#@#\Icons\Icon-ToolTip_Question.ico

; ----- Bar-Styles ------

; ---- Horizontal Bar Backgrounds ----
[Style_BarHBB]
BarOrientation=Horizontal
SolidColor=#Color5#,#Color5Alpha#
AntiAlias=1

; ---- Horizontal Bar Meters ----
[Style_BarHB]
BarOrientation=Horizontal
BarColor=#Color6#,#Color6Alpha#
X=r
Y=r
Solid=1
AntiAlias=1
DynamicVariables=1

; ---- Horizontal Bar Back - 60px ----
[Style_BarHBB_60]
BarOrientation=Horizontal
SolidColor=#Color5#,#Color5Alpha#
AntiAlias=1
W=60
H=8

; ---- Horizontal Bar - 60px ----
[Style_BarHB_60]
BarOrientation=Horizontal
BarColor=#Color6#,#Color6Alpha#
X=r
Y=r
Solid=1
AntiAlias=1
DynamicVariables=1
W=60
H=8

; ---- Horizontal Bar Back - 80px ----
[Style_BarHBB_80]
BarOrientation=Horizontal
SolidColor=#Color5#,#Color5Alpha#
AntiAlias=1
W=80
H=8

; ---- Horizontal Bar - 80px ----
[Style_BarHB_80]
BarOrientation=Horizontal
BarColor=#Color6#,#Color6Alpha#
X=r
Y=r
Solid=1
AntiAlias=1
DynamicVariables=1
W=80
H=8

; ---- Vertical Bar Backgrounds ----
[Style_BarVBBC2]
BarOrientation=Vertical
SolidColor=#Color5#,#Color5Alpha#
AntiAlias=1

; ---- Vertical Bar Meters ----
[Style_BarVBC2]
BarOrientation=Vertical
BarColor=#Color6#,#Color6Alpha#
X=r
Y=r
Solid=1
AntiAlias=1
DynamicVariables=1

; ---- Note: If you wan't a thin Line (Example 2px) just change the "LineStart" from 28 to 34! ----
; ---- Test it, and have fun! ----

; ---- Roundline Bar Backgrounds ----
[Style_BarRLBB]
LineColor=#Color5#,#Color5Alpha#
X=65
Y=60
LineStart=28
LineLength=36
Solid=1
AntiAlias=1

; ---- Roundline Bar Meters ----
[Style_BarRLB]
LineColor=#Color6#,#Color6Alpha#
X=65
Y=60
LineStart=28
LineLength=36
Solid=1
AntiAlias=1
DynamicVariables=1

; ---- Roundline Back 180 degree ----
[Style_BarRLBB_180]
LineColor=#Color5#,#Color5Alpha#
X=65
Y=60
StartAngle=(Rad(180))
RotationAngle=(Rad(180))
LineStart=28
LineLength=36
Solid=1
AntiAlias=1

[Style_BarRLB_180]
; ---- Roundline Bar 180 degree ----
LineColor=#Color6#,#Color6Alpha#
X=65
Y=60
StartAngle=(Rad(180))
RotationAngle=(Rad(180))
LineStart=28
LineLength=36
Solid=1
AntiAlias=1
DynamicVariables=1

; ---- Roundline Back 270 degree ----
[Style_BarRLBB_270]
LineColor=#Color5#,#Color5Alpha#
X=65
Y=60
StartAngle=(Rad(135))
RotationAngle=(Rad(270))
LineStart=28
LineLength=36
Solid=1
AntiAlias=1

; ---- Roundline Bar 270 degree
[Style_BarRLB_270]
LineColor=#Color6#,#Color6Alpha#
X=65
Y=60
StartAngle=(Rad(135))
RotationAngle=(Rad(270))
LineStart=28
LineLength=36
Solid=1
AntiAlias=1
DynamicVariables=1

; ---- Roundline Back 360 degree ----
[Style_BarRLBB_360]
LineColor=#Color5#,#Color5Alpha#
X=65
Y=61
StartAngle=(Rad(90))
RotationAngle=(Rad(360))
LineStart=28
LineLength=36
Solid=1
AntiAlias=1

; ---- Roundline Bar 360 degree
[Style_BarRLB_360]
LineColor=#Color6#,#Color6Alpha#
X=65
Y=61
StartAngle=(Rad(90))
RotationAngle=(Rad(360))
LineStart=28
LineLength=36
Solid=1
AntiAlias=1
DynamicVariables=1


; ---- Style for Graph ----
[Style_Graph]
GraphStart=Left
LineColor=#Color8#,#Color8Alpha#
LineCount=1
AutoScale=0
AntiAlias=1

; ---- Style for Graph W=60; H=15 ----
[Style_Graph_60_15]
GraphStart=Left
LineColor=#Color8#,#Color8Alpha#
LineCount=1
AutoScale=0
AntiAlias=1
W=60
H=15

; ---- Style for Graph W=80; H=15 ----
[Style_Graph_80_15]
GraphStart=Left
LineColor=#Color8#,#Color8Alpha#
LineCount=1
AutoScale=0
AntiAlias=1
W=80
H=15

; ---- Style for Graph W=80; H=25 ----
[Style_Graph_80_25]
GraphStart=Left
LineColor=#Color8#,#Color8Alpha#
LineCount=1
AutoScale=0
AntiAlias=1
W=80
H=25

; ---- Style for Histogram ----
[Style_Histogram]
GraphStart=Left
PrimaryColor=#Color8#,#Color8Alpha#
AutoScale=0
AntiAlias=1

; ---- Style for Histogram W=60; H=15 ----
[Style_Histogram_60_15]
GraphStart=Left
PrimaryColor=#Color8#,#Color8Alpha#
AutoScale=0
AntiAlias=1
W=60
H=15

; ---- Style for Histogram W=80; H=15  ----
[Style_Histogram_80_15]
GraphStart=Left
PrimaryColor=#Color8#,#Color8Alpha#
AutoScale=0
AntiAlias=1
W=80
H=15

; ---- Style for Histogram W=80; H=25  ----
[Style_Histogram_80_25]
GraphStart=Left
PrimaryColor=#Color8#,#Color8Alpha#
AutoScale=0
AntiAlias=1
W=80
H=25

; ----- Band-Styles ------

; ---- Vertical Band Meters 20px ----
[Style_BandVB_20]
BarOrientation=Vertical
BarColor=#Color7#,#Color7Alpha#
W=6
H=20
X=2R
Y=0r
;SolidColor=100,100,100,100

; ---- Vertical Band Meters 50px ----
[Style_BandVB_50]
BarOrientation=Vertical
BarColor=#Color7#,#Color7Alpha#
W=6
H=50
X=2R
Y=0r
;SolidColor=100,100,100,100

; ===== Styles for Color Palette =====

[Style_Color_Palette]
X=R
Y=r
DynamicVariables=1
Group=Palette

; --- Style for Background of Transparency Field ---
[Style_Meter_Color]
Shape2=Rectangle 0,52,32,16,0 | Fill Color #Color4# | StrokeWidth 0 | Stroke Color 0
DynamicVariables=1


; ==== WebRadio ====

; --- Button Station ---
[Style_BTN_Station]
Shape=Rectangle 0,0,32,32,2 | Fill Color #Color1#,0 | StrokeWidth 2 | Stroke Color #Color2#
DynamicVariables=1

; --- Button Station active ---
[Style_BTN_Station_A]
Shape=Rectangle 0,0,32,32,2 | Fill Color #Color4#,#Color4Alpha# | StrokeWidth 2 | Stroke Color #Color2#
DynamicVariables=1

; ---- Station Names ----
[Style_Station_Name]
X=([Label_Station_Name:X])
Y=([Label_Station_Name:Y]+22)
W=100
H=18
ClipString=1
SolidColor=#Color4#,#Color4Alpha#
DynamicVariables=1

; ---- Stream-Links ----
[Style_Station_Stream]
X=([Label_Station_Stream:X])
Y=([Label_Station_Stream:Y]+22)
W=253
H=18
ClipString=1
SolidColor=#Color4#,#Color4Alpha#
DynamicVariables=1

; ---- Station Names ----
[Style_Station_Image]
X=([Label_Station_Image:X])
Y=([Label_Station_Image:Y]+22)
W=100
H=18
ClipString=1
SolidColor=#Color4#,#Color4Alpha#
DynamicVariables=1

; ---- Stream-Links ----
[Style_Station_URL]
X=([Label_Station_URL:X])
Y=([Label_Station_URL:Y]+22)
W=253
H=18
ClipString=1
SolidColor=#Color4#,#Color4Alpha#
DynamicVariables=1

