[Rainmeter]


[Metadata]
Name=Hex H Suite
Author=Zerogate309
Information=Variables for the Suite
FileVersion=2022-12
License=Creative Commons Attribution-Non-Commercial-Share Alike 4.0

[Variables]
; ############ Skin Variables ############
; ############ Color Palette ############
; ############ Skin Colors ############
; ############ Fonts ############
; ############ Font Sizes ############
; ############ Drives ############
; ############ Units ############
; ############ Content Variables ############
; --- Player ---
; --- Search Engine ---
; ---- Ping IP-Adress ----
; ---- Folder Links ----
; ---- Web-Links ----
; ---- Appointments ----
; ---- TimeZones ----
; ---- WebRadio ----

; ############ Skin Variables ############

; ---- Padding in px of Skins ----
Padding=10

; ############ Color Palette ############
; --- This are the Colors of the Color Palette ---
; --- Format is: Red, Green, Blue with no Transparency (Alpha) ---
; --- And the Name of the Color which is displayed when you drive over the color palette ---


ColorERROR=77,100,141

ColorPal_01=30,40,50
ColorTxt_01=Midnight

ColorPal_02=77,100,141
ColorTxt_02=Blueberry

ColorPal_03=100,112,128
ColorTxt_03=Grey

ColorPal_04=208,225,249
ColorTxt_04=Periwinkle

ColorPal_05=2,28,30
ColorTxt_05=Blue Black

ColorPal_06=0,68,69
ColorTxt_06=Cadet Blue

ColorPal_07=44,120,115
ColorTxt_07=Rain

ColorPal_08=111,185,143
ColorTxt_08=Greenery

ColorPal_09=46,52,64
ColorTxt_09=nord0

ColorPal_10=59,66,82
ColorTxt_10=nord1

ColorPal_11=67,76,94
ColorTxt_11=nord2

ColorPal_12=76,86,106
ColorTxt_12=nord3

ColorPal_13=216,222,233
ColorTxt_13=nord4

ColorPal_14=229,233,240
ColorTxt_14=nord5

ColorPal_15=236,239,244
ColorTxt_15=nord6

ColorPal_16=143,188,187
ColorTxt_16=nord7

ColorPal_17=136,192,208
ColorTxt_17=nord8

ColorPal_18=129,161,193
ColorTxt_18=nord9

ColorPal_19=94,129,172
ColorTxt_19=nord10

ColorPal_20=191,97,106
ColorTxt_20=nord11

ColorPal_21=208,135,112
ColorTxt_21=nord12

ColorPal_22=235,203,139
ColorTxt_22=nord13

ColorPal_23=163,190,140
ColorTxt_23=nord14

ColorPal_24=180,142,173
ColorTxt_24=nord15

ColorPal_25=0,0,0
ColorTxt_25=Black

ColorPal_26=160,40,40
ColorTxt_26=Red

ColorPal_27=255,140,0
ColorTxt_27=Orange

ColorPal_28=240,195,0
ColorTxt_28=Yellow

ColorPal_29=31,150,66
ColorTxt_29=Green

ColorPal_30=120,30,180
ColorTxt_30=Violett

ColorPal_31=0,0,240
ColorTxt_31=Blue

ColorPal_32=140,70,20
ColorTxt_32=Brown

ColorPal_33=175,68,37
ColorTxt_33=Ceyenne

ColorPal_34=102,46,28
ColorTxt_34=Cinnamon

ColorPal_35=235,220,178
ColorTxt_35=Cream

ColorPal_36=201,166,107
ColorTxt_36=Caramel

ColorPal_37=100,100,100
ColorTxt_37=Your Choice

ColorPal_38=100,100,100
ColorTxt_38=Your Choice

ColorPal_39=100,100,100
ColorTxt_39=Your Choice

ColorPal_40=100,100,100
ColorTxt_40=Your Choice

ColorPal_41=100,100,100
ColorTxt_41=Your Choice

ColorPal_42=100,100,100
ColorTxt_42=Your Choice

ColorPal_43=100,100,100
ColorTxt_43=Your Choice

ColorPal_44=100,100,100
ColorTxt_44=Your Choice

ColorPal_45=100,100,100
ColorTxt_45=Your Choice

ColorPal_46=100,100,100
ColorTxt_46=Your Choice

ColorPal_47=100,100,100
ColorTxt_47=Your Choice

ColorPal_48=100,100,100
ColorTxt_48=RGB-Color-Picker

; ############ Skin Colors ############

; --- Color 1 - (for Background)
Color1=30,40,50
Color1Alpha=255

; --- Color 2  - (for Frames)
Color2=77,100,141
Color2Alpha=255

; --- Color 3 - (for Text Highlight)
Color3=208,225,249
Color3Alpha=255

; --- Color 4 - (for Normal Text)
Color4=100,112,128
Color4Alpha=255

; --- Color 5 - (for Bar Background)
Color5=77,100,141
Color5Alpha=255

; --- Color 6 - (for Bar)
Color6=208,225,249
Color6Alpha=255

; --- Color 7 - (for Band)
Color7=100,112,128
Color7Alpha=255

; --- Color 8 - (for Graph)
Color8=100,112,128
Color8Alpha=255

; --- Color 9 - (for Icon)
Color9=77,100,141
Color9Alpha=255

; --- Color B - (for Screen Border)
ColorB=100,112,128
ColorBAlpha=128

; --- Color Up & Down for Stocks
ColorUp=51,204,51,255
ColorDown=204,51,51,255

; --- Color High (Green) Mid (Yellow) Low (Red)
ColorHigh=51,204,51,255
ColorMid=230,230,20,255
ColorLow=204,51,51,255

; ############ Fonts ############
FontFace_1=Elemental End
FontFace_2=Tahoma

; ############ Font Sizes ############
FontSize_20 = 20
FontSize_18 = 18
FontSize_16 = 16
FontSize_15 = 15
FontSize_14 = 14
FontSize_13 = 13
FontSize_12 = 12
FontSize_11 = 11
FontSize_10 = 10
FontSize_09 = 09
FontSize_08 = 08
FontSize_07 = 07
FontSize_06 = 06


; ############ Drives ############

Drive_00=b
Drive_00_Icon=Icon-Drive_00

Drive_01=c
Drive_01_Icon=Icon-Drive_01

Drive_02=d
Drive_02_Icon=Icon-Drive_02

Drive_03=e
Drive_03_Icon=Icon-Drive_02

Drive_04=f
Drive_04_Icon=Icon-Drive_03

Drive_05=g
Drive_05_Icon=Icon-Drive_04

Drive_06=h
Drive_06_Icon=Icon-Drive_04

Drive_07=i
Drive_07_Icon=Icon-Drive_05

Drive_08=j
Drive_08_Icon=Icon-Drive_05

Drive_09=k
Drive_09_Icon=Icon-Drive_06

Drive_10=x
Drive_10_Icon=Icon-Drive_07

Drive_11=y
Drive_11_Icon=Icon-Drive_07

Drive_12=z
Drive_12_Icon=Icon-Drive_07

; ----- Language -----

;Language=en-US
Language=de-DE

; ############ Units ############

; ---- 12 = 12 hr | 24 = 24 hr ----
FormatTime=24

; ---- C = Celsius | F = Fahrenheit ----
UnitTemp=C

; --- Symbol Variables ---
Degrees=[\x00B0]

; ---- Location for Weather.com ----
Location=GMXX0063


; ############ Content Variables ############

; --- Player ---
PlayerName=Foobar2000
PlayerNamePATH=Foobar2000.exe

; --- Search Engine ---
SearchEngine=Google

; ---- Ping IP-Adress ----
Ping=192.168.0.81

; ---- Folder Links ----
Folder_1_Name=_Downloads
Folder_1_Link=D:\_Downloads

Folder_2_Name=_Projects
Folder_2_Link=D:\_Projects

Folder_3_Name=_Backup
Folder_3_Link=D:\_Backup

Folder_4_Name=_Downloads
Folder_4_Link=D:\_Downloads

Folder_5_Name=_Projects
Folder_5_Link=D:\_Projects

Folder_6_Name=_Backup
Folder_6_Link=D:\_Backup


; ---- Web-Links ----
Web_Link_1_Name=Google
Web_Link_1_Link=https://www.google.de/

Web_Link_2_Name=YouTube
Web_Link_2_Link=https://www.youtube.com

Web_Link_3_Name=dict.cc
Web_Link_3_Link=https://www.dict.cc/

Web_Link_4_Name=Rainm.Manual
Web_Link_4_Link=https://docs.rainmeter.net/manual/

Web_Link_5_Name=Deviant Art
Web_Link_5_Link=https://www.deviantart.com/

Web_Link_6_Name=Flaticon
Web_Link_6_Link=https://www.flaticon.com

Web_Link_7_Name=Google
Web_Link_7_Link=https://www.google.de/

Web_Link_8_Name=YouTube
Web_Link_8_Link=https://www.youtube.com


; ---- Appointments ----
Date_1_Name=23.7.-3.8. Holiday
Date_1_Note=until 23.07.20
Date_1_Link=https://www.google.de/

Date_2_Name=25.12. X-Mas
Date_2_Note=Marry X-Mas!
Date_2_Link=https://www.google.de/

Date_3_Name=31.12. Party
Date_3_Note=Happy New Year!
Date_3_Link=https://www.google.de/

TimeZone1_Dif=+8
TimeZone1_Place=Tokyo

TimeZone2_Dif=+1
TimeZone2_Place=Paris

TimeZone3_Dif=-5
TimeZone3_Place=New York

; ---- WebRadio ----
;-- Webradio Basic Settings ----------------------------------------------------------------------- 
Path_To_VLC			=C:\Program Files\VideoLAN\VLC\vlc.exe
Path_To_Stations	=#@#\Icons\WebRadioStations\
;-- Active Station -------------------------------------------------------------------------------- 
Station_A_Name		=MABU Beatz Radio
Station_A_Image		=MABU Beatz Radio.png
Station_A_Stream	=https://audio.mabu-beatz-radio.com:8003/dub.m3u
Station_A_URL       =https://mabu-beatz-radio.com/

;-- Stations List --------------------------------------------------------------------------------- 
Station_1_Name		=UnserRadio
Station_1_Image		=UnserRadio.png
Station_1_Stream	=http://rs4.stream24.net/unser-radio.mp3
Station_1_URL       =https://onlineradiobox.com/de/unserradio/playlist/

Station_2_Name		=MABU Beatz Radio - Dub Techno
Station_2_Image		=MABU Beatz Radio.png
Station_2_Stream	=https://audio.mabu-beatz-radio.com:8003/dub.m3u
Station_2_URL       =https://mabu-beatz-radio.com/

Station_3_Name		=Bayern 3
Station_3_Image		=Bayern3.png
Station_3_Stream	=http://br-br3-live.cast.addradio.de/br/br3/live/mp3/128/stream.mp3
Station_3_URL       =http://www.br.de/radio/bayern-3/bayern-3-playlist-musiktitel-recherche/index.html

Station_4_Name		=Antenne Top40
Station_4_Image		=AntenneTop40.png
Station_4_Stream	=http://mp3channels.webradio.antenne.de/top-40
Station_4_URL       =http://www.webradio.de/antenne-bayern/top-40

Station_5_Name		=Rock Antenne
Station_5_Image		=RockAntenne.png
Station_5_Stream	=http://mp3channels.webradio.antenne.de/rockantenne
Station_5_URL       =http://www.webradio.de/antenne-bayern/rock-antenne

Station_6_Name		=Top 100 Station
Station_6_Image		=Top100Station.png
Station_6_Stream	=http://91.250.76.18
Station_6_URL       =http://www.top100station.de

Station_7_Name		=Technobase.FM
Station_7_Image		=TechnobaseFM.png
Station_7_Stream	=http://listen.technobase.fm/tunein-dsl-pls
Station_7_URL       =https://www.technobase.fm/tracklist

Station_8_Name		=Radio Schizoid
Station_8_Image		=Radio Schizoid - Dub Techno.png
Station_8_Stream	=http://schizoid.in/schizoid-dub.pls
Station_8_URL       =http://schizoid.in/


